### ISSUE TITLE
Missing emoji icons

### ISSUE THREAD

**Issue by jsumners** [jsumners/alfred-emoji#1]
The following emoji are missing icons due the Apple emoji font not recognizing them:

+ octocat
+ shipit
+ bowtie
+ neckbeard
+ trollface
+ godmode
+ goberserk
+ finnadie
+ feelsgood
+ rage1
+ rage2
+ rage3
+ rage4
+ suspect
+ hurtrealbad

They will need special consideration if they are to work correctly. I'm not an artist, so someone else will have to step up.

**Comment by rmm5t** [comment]
First, thanks for taking on this project after the former one went unmaintained. 

personally, I'd be cool with just eliminating these special "github" emojis and making the workflow limited to just standard emoji.

**Comment by jsumners** [comment]
Well, they are essentially eliminated whilst this issue remains untouched :)

**Comment by rmm5t** [comment]
> Well, they are essentially eliminated whilst this issue remains untouched :)

Not exactly:

<img width="589" alt="monosnap 2018-01-05 16-54-41" src="https://user-images.githubusercontent.com/740/34633402-399b9260-f239-11e7-9da5-e6f0fa34b808.png">

**Comment by jsumners** [comment]
Would you like to submit a PR that fixes that?

**Comment by rmm5t** [comment]
> Would you like to submit a PR that fixes that?

👍 Sure thing. See #3.
