### ISSUE TITLE
Emoji choices never appear

### ISSUE THREAD

**Issue by glgray** [jsumners/alfred-emoji#100]
I tried using alfred-emoji for the first time in some months, and it just showed “Loading results...”. So I checked and saw that I was running an old version, so I downloaded and installed v2.0.1. When I invoke it in Alfred, I wait and wait, and it still just says, “Loading results...”. Here is a screenshot.

<img width="588" alt="Screenshot 2022-12-19 at 8 07 10 AM" src="https://user-images.githubusercontent.com/49663/208433849-7e80b407-c8e3-4879-91f1-2270cfbd50da.png">

What am I doing wrong?

**Comment by jsumners** [comment]
What version of Alfred are you using?

**Comment by glgray** [comment]
Sorry, I should have mentioned that. v5.0.6

**Comment by jsumners** [comment]
You could try running the workflow while the debugger console (https://www.alfredapp.com/help/workflows/advanced/debugger/) to see if anything is printed there. But I suspect nothing will show.

It seems there are times when Alfred is taking a long while to populate its cache from the workflow. I don't know of any way to force it to work (maybe @vitorgalvao has a suggestion). The best I can suggest is to completely remove the workflow and reinstall it. That may be enough to jump start things.

**Comment by vitorgalvao** [comment]
You’re calling `osascript` from `bash`, Alfred simply asks the system to run that and doesn’t touch anything else. Whatever cache there is—both writing and reading it—will be handled by the workflow’s code, I see nowhere where Alfred itself would be interfering.

**Comment by glgray** [comment]
Before reinstalling, I tried invoking it several more times, and the search results started appearing. Problem solved. Thank you all for your help and suggestions.

**Comment by jsumners** [comment]
> You’re calling `osascript` from `bash`, Alfred simply asks the system to run that and doesn’t touch anything else. Whatever cache there is—both writing and reading it—will be handled by the workflow’s code, I see nowhere where Alfred itself would be interfering.

I am referring to the "learning" feature shown here:

![image](https://user-images.githubusercontent.com/321201/208466327-01c6ea0f-2051-4c79-8141-cc66718b71b8.png)

**Comment by vitorgalvao** [comment]
That just [affects ordering](https://www.alfredapp.com/help/kb/understanding-result-ordering/), it has no influence in this situation.
