### ISSUE TITLE
doesn't work on Ventura 13.3(beta)

### ISSUE THREAD

**Issue by AARONAHN** [jsumners/alfred-emoji#102]
thanks for creating and maintaining the workflow. this is absolutely one of my favorite Alfred workflows.

i recently updated to Ventura 13.3 beta and the workflow doesn't work since.
the keyword itself seems to be recognized by Alfred but unable to search the emoji.

![emoji](https://user-images.githubusercontent.com/20138592/224522881-03e8649f-7946-4dff-8d53-3e4430542f30.gif)

tried reinstalling the workflow and Alfred, but the issue persists.

here's what debugger says:
```
[12:12:07.183] Logging Started...
[12:12:14.693] Emoji search[Script Filter] Queuing argument ''
[12:12:14.902] Emoji search[Script Filter] Script with argv '' finished
[12:12:14.908] Emoji search[Script Filter] Inspection is enabled by default for process or parent application with deprecated 'com.apple.webinspector.allow' entitlement. Use `inspectable` API to enable inspection instead.
```

**Comment by jsumners** [comment]
I don't have a system with that macOS version, and likely won't for some time (seriously, I just updated from 10.15 to 13 a week ago).

It seems to me like the workflow is not invoking the JXA script correctly. I would try navigating to the workflow's install directory and attempt to run the search script directly with JXA:

1. Right click the workflow in the Alfed workflows pane
2. Choose "Open In Terminal"
3. `osascript -l JavaScript emoji.js "monkey"`

That should show a big blob of JSON text with "monkey" emojis scattered throughout it. If not, what error does it show?

Also, what version of the workflow are you using?

**Comment by AARONAHN** [comment]
I get the following result:
```
Inspection is enabled by default for process or parent application with deprecated 'com.apple.webinspector.allow' entitlement. Use `inspectable` API to enable inspection instead.
{"items":[{"uid":"see-no-evil monkey","title":"see-no-evil monkey","subtitle":"Copy \"🙈\" (see-no-evil monkey) to clipboard","arg":"🙈","autocomplete":"see-no-evil monkey","icon":{"path":"./icons/see_no_evil_monkey.png"},"mods":{"alt":{"subtitle":"Copy \":see_no_evil_monkey:\" (🙈) to clipboard","arg":":see_no_evil_monkey:","icon":{"path":"./icons/see_no_evil_monkey.png"}},"shift":{"subtitle":"Copy \"🙈\" (see-no-evil monkey) to clipboard","arg":"🙈","icon":{"path":"./icons/see_no_evil_monkey.png"}},"ctrl":{"subtitle":"Copy \"U+1F648\" (🙈) to clipboard","arg":"U+1F648","icon":{"path":"./icons/see_no_evil_monkey.png"}}}},{"uid":"hear-no-evil monkey","title":"hear-no-evil monkey","subtitle":"Copy \"🙉\" (hear-no-evil monkey) to clipboard","arg":"🙉","autocomplete":"hear-no-evil monkey","icon":{"path":"./icons/hear_no_evil_monkey.png"},"mods":{"alt":{"subtitle":"Copy \":hear_no_evil_monkey:\" (🙉) to clipboard","arg":":hear_no_evil_monkey:","icon":{"path":"./icons/hear_no_evil_monkey.png"}},"shift":{"subtitle":"Copy \"🙉\" (hear-no-evil monkey) to clipboard","arg":"🙉","icon":{"path":"./icons/hear_no_evil_monkey.png"}},"ctrl":{"subtitle":"Copy \"U+1F649\" (🙉) to clipboard","arg":"U+1F649","icon":{"path":"./icons/hear_no_evil_monkey.png"}}}},{"uid":"speak-no-evil monkey","title":"speak-no-evil monkey","subtitle":"Copy \"🙊\" (speak-no-evil monkey) to clipboard","arg":"🙊","autocomplete":"speak-no-evil monkey","icon":{"path":"./icons/speak_no_evil_monkey.png"},"mods":{"alt":{"subtitle":"Copy \":speak_no_evil_monkey:\" (🙊) to clipboard","arg":":speak_no_evil_monkey:","icon":{"path":"./icons/speak_no_evil_monkey.png"}},"shift":{"subtitle":"Copy \"🙊\" (speak-no-evil monkey) to clipboard","arg":"🙊","icon":{"path":"./icons/speak_no_evil_monkey.png"}},"ctrl":{"subtitle":"Copy \"U+1F64A\" (🙊) to clipboard","arg":"U+1F64A","icon":{"path":"./icons/speak_no_evil_monkey.png"}}}},{"uid":"monkey","title":"monkey","subtitle":"Copy \"🐒\" (monkey) to clipboard","arg":"🐒","autocomplete":"monkey","icon":{"path":"./icons/monkey.png"},"mods":{"alt":{"subtitle":"Copy \":monkey:\" (🐒) to clipboard","arg":":monkey:","icon":{"path":"./icons/monkey.png"}},"shift":{"subtitle":"Copy \"🐒\" (monkey) to clipboard","arg":"🐒","icon":{"path":"./icons/monkey.png"}},"ctrl":{"subtitle":"Copy \"U+1F412\" (🐒) to clipboard","arg":"U+1F412","icon":{"path":"./icons/monkey.png"}}}},{"uid":"banana","title":"banana","subtitle":"Copy \"🍌\" (banana) to clipboard","arg":"🍌","autocomplete":"banana","icon":{"path":"./icons/banana.png"},"mods":{"alt":{"subtitle":"Copy \":banana:\" (🍌) to clipboard","arg":":banana:","icon":{"path":"./icons/banana.png"}},"shift":{"subtitle":"Copy \"🍌\" (banana) to clipboard","arg":"🍌","icon":{"path":"./icons/banana.png"}},"ctrl":{"subtitle":"Copy \"U+1F34C\" (🍌) to clipboard","arg":"U+1F34C","icon":{"path":"./icons/banana.png"}}}},{"uid":"monkey face","title":"monkey face","subtitle":"Copy \"🐵\" (monkey face) to clipboard","arg":"🐵","autocomplete":"monkey face","icon":{"path":"./icons/monkey_face.png"},"mods":{"alt":{"subtitle":"Copy \":monkey_face:\" (🐵) to clipboard","arg":":monkey_face:","icon":{"path":"./icons/monkey_face.png"}},"shift":{"subtitle":"Copy \"🐵\" (monkey face) to clipboard","arg":"🐵","icon":{"path":"./icons/monkey_face.png"}},"ctrl":{"subtitle":"Copy \"U+1F435\" (🐵) to clipboard","arg":"U+1F435","icon":{"path":"./icons/monkey_face.png"}}}}]
```

I'm using v2.0.1 now.

**Comment by jsumners** [comment]
This indicates to me that the workflow is working as designed. I'd suggest asking on the Alfred forums about incompatibility between Alfred and macOS 13.3.

However, one other thing I'd be interested in seeing is the main workflow execution unit in Alfred. Does it show any errors?

![Alfred Preferences 2023-03-14 10-19-18](https://user-images.githubusercontent.com/321201/225030895-f07540c4-363a-470d-a86b-a230babd6d8c.png)

^ that should result in:

![Monosnap 2023-03-14 10-21-34](https://user-images.githubusercontent.com/321201/225031023-af6ba533-416c-4c33-af7b-c4c33f839713.png)

**Comment by AARONAHN** [comment]
thanks for checking out. the workflow works fine on my another macbook running on 13.1 so Alfred might have some incompatibility issues with 13.3.

also, I couldn't find any error shown in Script Filter:
<img width="805" alt="image" src="https://user-images.githubusercontent.com/20138592/225120152-53587f29-eb0f-4cc2-a4a0-a79ab9412296.png">

**Comment by gfviegas** [comment]
Im experiencing the same in MacOS Ventura - Version 13.3 Beta (22E5236f)

If you have any luck finding a workaround, @AARONAHN please lemme know! :) (traditional smile as I can't copy emojis from alfred, lol)

**Comment by jsumners** [comment]
I thought I might install 13.3 in a UTM virtual machine, but Apple doesn't seem to provide the dmg/iso for it without enrolling some actual computer in a beta program.

**Comment by AARONAHN** [comment]
@gfviegas @jsumners i updated to 13.3(22E252) today and now it works fine 😃(now i can easily copy emojis!) i guess the issue is only for the specific version of macOS.

**Comment by gfviegas** [comment]
After updating my mac, I can confirm that it's working properly again 🥳

**Comment by gfviegas** [comment]
@jsumners I suppose you can close this issue. It's one of those edge cases that will happen when you are in a beta version of OS
