### ISSUE TITLE
Missing emoji icons

### ISSUE THREAD

**Issue by circumeo** [jsumners/alfred-emoji#103]
<img width="778" alt="스크린샷 2023-06-16 오후 2 39 08" src="https://github.com/jsumners/alfred-emoji/assets/76243664/0de00ed7-e629-4261-bba3-a04bc9d1262b">

Is there any way to solve this problem?

**Comment by jsumners** [comment]
I believe this is a duplicate of https://github.com/jsumners/alfred-emoji/issues/78

**Comment by circumeo** [comment]
> I believe this is a duplicate of #78

Yeah You're right I'm so sorry
I don't think I understood #78 very well...

**Comment by jsumners** [comment]
I agree the situation is not ideal. I hope to write my own parser of the Unicode documents at some point, but it's pretty far down on my priority list.
