### ISSUE TITLE
New Emojis in Version 15.0 do not display icons.

### ISSUE THREAD

**Issue by MaterialDan** [jsumners/alfred-emoji#105]
Hi jsumners,

On my system, the [new emojis in version 15.0](https://emojipedia.org/emoji-15.0) do not display the image of the emoji to the left of the description. Is there something I can do to resolve the ‘blanks’?

System: Ventura 13.6.3; Alfred 5.1.4 [2195]

<img width="768" alt="SS-20231224--uokt" src="https://github.com/jsumners/alfred-emoji/assets/134036120/6d2ce4dd-7c9e-4e43-bed8-065fb5c5bcb7">

**Comment by jsumners** [comment]
https://github.com/jsumners/alfred-emoji/blob/55d39e26717ce65369dce0678234666e2741a3fb/Readme.md?plain=1#L10-L19

https://github.com/actions/runner-images/blob/08d10be70d3c2c3cc99b0dc4affd1981e6fafdc7/README.md?plain=1#L20-L30

**Comment by jsumners** [comment]
Try https://github.com/jsumners/alfred-emoji/releases/tag/v2.2.0
