### ISSUE TITLE
Emoticons

### ISSUE THREAD

**Issue by Qhilm** [jsumners/alfred-emoji#106]
Amazing add-on you have, I use it every day!

It's a feature request: being able to search for fun emoticons like the shrug emoticon ¯\_(ツ)_/¯ would be nice.

**Comment by jsumners** [comment]
I'm glad you find the workflow useful. The way this workflow works is by utilizing a font shipped with macOS to generate recognizable emoji images (for the workflow ui) based upon the list of emjoi exported from https://github.com/muan/emojilib. I do not know of any such resources for the requested feature.

You are welcome to open a PR to provide this feature if you're able to solve the above. But as it is, I'll be closing this as not planned.
