### ISSUE TITLE
Add hotkey input

### ISSUE THREAD

**Issue by vdesabou** [jsumners/alfred-emoji#16]
Nice workflow 😃

Could you add hotkey input like below, so that we can easily invoke the workflow?

![screenshot 2018-01-12 at 13 12 03](https://user-images.githubusercontent.com/4061923/34874662-46a7e4ac-f79a-11e7-91a1-b9acace856e8.jpg)

**Comment by jsumners** [comment]
Do you have a suggested one? I just use cmd+space to bring up Alfred for all the Alfred things.

**Comment by vdesabou** [comment]
I personnel use
![screenshot 2018-01-12 at 13 25 16](https://user-images.githubusercontent.com/4061923/34875075-107925ce-f79c-11e7-96b5-85fa545e97fc.jpg)

But I think you should let it empty: it will allow users to define what they want.

**Comment by jsumners** [comment]
If you load up a workflow with a blank hotkey item does it require to do anything? Or does it simply make it possible to do something?

**Comment by vdesabou** [comment]
No it does not require anything.

End user can fill their own hotkey if they want, this is optional. 
And when user update workflow, their hotkey is not replaced.

**Comment by rmm5t** [comment]
> But I think you should let it empty: it will allow users to define what they want.

Agreed. I think leaving the hotkey empty is the common convention amongst workflows out there.
