### ISSUE TITLE
Better multi-word search support

### ISSUE THREAD

**Issue by rmm5t** [jsumners/alfred-emoji#17]
[This was suggested in the forums](https://www.alfredforum.com/topic/11126-alfred-emoji-search-emojis-by-name-or-keyword/?page=2&tab=comments#comment-58074):

> Also it would be nice if this matched for `open_book`. So you are not forced to type the underscore every time.
>
> ![5a58c8c0cabe2_2018-01-12at15_39 png 6479a4fb068551fd02337d6e0363d38a](https://user-images.githubusercontent.com/740/34881093-cf3aca58-f76f-11e7-840e-3f108e4544a5.png)

I tend to agree, but I also think it would be beneficial to be able to search for `book open` and get the same result as `open_book`. In other words, multi-word queries. 

Right now, we just strip whitespace, but I think we can do better. I'm going to play with a PR to improve this soon.

**Comment by jsumners** [comment]
FYI: my idea behind stripping the whitespace was to normalize the search terms. With your recent addition of `"` around the search term, this may not be necessary.

**Comment by rmm5t** [comment]
Yeah, there are a lot of different options that can be taken here. For now, I'm just going to make sure that our existing regression tests remains green while adding basic support for obvious things like "open book" or "plant nature."

**Comment by rmm5t** [comment]
Btw, I still think single word searches will be the most common.
