### ISSUE TITLE
Swapping Usage behaviours?

### ISSUE THREAD

**Issue by n0mar** [jsumners/alfred-emoji#24]
Hi!

Just wondering how it would be possible for me to change the <kbd>return</kbd> and <kbd>cmd</kbd>+<kbd>return</kbd> gestures. Instead, I would like <kbd>return</kbd> to simply paste the symbol, and <kbd>cmd</kbd>+<kbd>return</kbd> to copy the symbol.

Thanks for your work!

**Comment by jsumners** [comment]
You would have to modify the workflow.

**Comment by rmm5t** [comment]
Hi @n0mar, It's not possible to fully swap the two hotkey combinations, but it is possible to make them _both_ paste the symbol. 

But first, I would suggest using a keyword snippet instead. If the workflow is instantiated from a keyword snippet, it automatically pastes.

However, if you just want <kbd>return</kbd> to paste by default, you can effectively override this behavior with an environment variable. Assuming that you have at least v1.6.0 installed, just set the `snippetapp` environment variable (to any value) in the workflow configuration. This changes the behavior to always paste the emoji character regardless of how the workflow is instantiated.

<img width="739" alt="monosnap 2018-02-12 07-52-29" src="https://user-images.githubusercontent.com/740/36102600-085adbc6-0fca-11e8-91f2-e333c16a7816.png">

For more information, see this forum thread comment:
https://www.alfredforum.com/topic/11126-alfred-emoji-search-emojis-by-name-or-keyword/?page=2&tab=comments#comment-58339
