### ISSUE TITLE
macOS 10.14 emoji update

### ISSUE THREAD

**Issue by jsumners** [jsumners/alfred-emoji#28]
With macOS 10.14 being released today there should be an updated release of alfred-emoji to go along with it so that the new emoji in the OS is included. However, I do not currently have a system that I will be able to install 10.14 on and issue an updated build from.

@rmm5t do you have a system available for this?

**Comment by rmm5t** [comment]
Yes, I have a system available for upgrade. I probably won’t upgrade until later this week or next, though.

**Comment by jsumners** [comment]
Sounds good. Take your time 🙂
