### ISSUE TITLE
skin tone

### ISSUE THREAD

**Issue by lazywei** [jsumners/alfred-emoji#31]
Hi, wondering if there is anyway we can change the skin tone used in the emoji through this workflow?
Thanks

**Comment by jsumners** [comment]
That's not an implemented feature. If you would like to contribute it, we welcome PRs.

**Comment by jsumners** [comment]
Released as v1.9.0.

**Comment by jphorn** [comment]
Thank you @Glennmen for this PR and your contribution. I really missed having this in alfred-emoji, so really happy this was merged. And thank you @jsumners for all your hard work as well.
