### ISSUE TITLE
Running on old macOS (10.11)

### ISSUE THREAD

**Issue by adamkiss** [jsumners/alfred-emoji#34]
Hi guys,

I had a trouble running this probably due to node bundled with osascript on macOS 10.11? I am not sure. I made it work by:

- running it with local node (not osascript)
- putting back removing first two `process.argv`
- and let Alfred do the filtering

This isn't as much as issue, as maybe something for other users to know or put to your readme? I am not sure. If you want, I can also change the updater URLs and do a separate release, though I am not sure how replicable my setup is — I was simply running `yarn load` until I got it working :D

My modifications are here: https://github.com/adamkiss/alfred-emoji

**Comment by adamkiss** [comment]
Ah, I forgot… Thank you for this workflow :D 🎉🌸

**Comment by rmm5t** [comment]
@adamkiss Thanks for the report and sharing the workaround. 

macOS 10.11, eh? I'm guessing there are also a lot of indexed emojis that you're not able to use/see. I have another mac that's dedicated to a particular client and I'm required to keep that running macOS 10.13, and the missing emoji annoy me on that version alone.

**Comment by adamkiss** [comment]
@rmm5t If I really tried, I could at least generate the alfred previews (which are now empty for nonexistent emoji) on another mac, but yes. Until I switch around so eme parts, 11 it is :)

**Comment by jsumners** [comment]
Given the research in https://github.com/nodejs/build/issues/1030#issuecomment-361794353 I would say 10.11 is basically EOL. Current rumor is that 10.15 will release sometime in October -- http://osxdaily.com/2019/09/11/macos-catalina-to-be-released-in-october/

**Comment by adamkiss** [comment]
@jsumners Don't I feel it everyday 😄 I just wanted to note how to run this for other users who are lazy/unable to update.
