### ISSUE TITLE
macOS 10.15 (Catalina) emoji update

### ISSUE THREAD

**Issue by jsumners** [jsumners/alfred-emoji#35]
I am certain there are new emoji in the latest macOS release, 10.15. I'm not sure when I will update to the new OS. When I do, I will issue a new workflow release with the added emoji. It could be quite some time, however. I'm not keen to update to 10.15 any time soon.

**Comment by rmm5t** [comment]
I should have a machine that will be updated to macOS 10.15 within the next couple weeks or so; however, aren't we waiting on a new [emojilib](https://github.com/muan/emojilib) release first anyway?

**Comment by jsumners** [comment]
Probably. I was just putting this issue out as a notice to users. If you get to it before me, awesome. 

I _might_ pick up Parallels so I can run 10.15 in a VM for a while to test things out. If so, I’ll be able to do this sooner than later. We shall see.

**Comment by bhanquier** [comment]
Hi, 
I'm no coder, but I guess updating the constantly evolving emojis must be a hassle. I've just realized that the "pinching hand" was absent from the current set here. 
So I was wondering if you were aware of the workflow - seemingly dead now - Emoji Taco (https://github.com/jeeftor/EmojiTaco/).
It had a nice update feature, that I thought maybe you could get some inspiration from, if not a straightforward working solution. 
Cheers.

**Comment by jsumners** [comment]
I have a new MBP 16" arriving around the end of next week/beginning of the following week. If I don't get around to an update via Parallels before then, I'll issue an update shortly thereafter.

@bhanquier This is an OSS project. It is provided on an as-able / as-willing basis. In order to include new emoji in the workflow, the workflow must be re-built on a system running the version of macOS that includes the emoji. Until someone has access to such a machine, and time to work on the update, such an update to the workflow cannot be released. The workflow you have linked works in essentially the same manner, it just sources emoji from a different data set.

**Comment by bhanquier** [comment]
> I have a new MBP 16" arriving around the end of next week/beginning of the following week. If I don't get around to an update via Parallels before then, I'll issue an update shortly thereafter.
> 
> @bhanquier This is an OSS project. It is provided on an as-able / as-willing basis. In order to include new emoji in the workflow, the workflow must be re-built on a system running the version of macOS that includes the emoji. Until someone has access to such a machine, and time to work on the update, such an update to the workflow cannot be released. The workflow you have linked works in essentially the same manner, it just sources emoji from a different data set.

Got it! Thanks for the explanation 🙏

**Comment by jsumners** [comment]
I do not believe we can update until this issue is resolved -- https://github.com/muan/emojilib/pull/178

That, or if we can find another equivalent module.

**Comment by jsumners** [comment]
Note: v1.9.0 is built on macOS 10.15, but that doesn't mean it includes any of the new emoji. I need to find time/energy to build a library to track the unicode releases.

**Comment by waynehoover** [comment]
Would love to see the new emoji in this excellent library, is there anything I can do to help?

**Comment by jsumners** [comment]
It’s all pretty well documented in this thread. Nothing has changed.

**Comment by jsumners** [comment]
The emojilib issue has been resolved and released as v3.0.0. Migration notes can be found at https://github.com/muan/emojilib/releases/tag/v3.0.0

**Comment by jsumners** [comment]
Resolved by #72
