### ISSUE TITLE
Query defaults to Google search

### ISSUE THREAD

**Issue by dsrjarman** [jsumners/alfred-emoji#36]
I got this workflow working on one machine, but am having issues with another! Maybe a setting I've missed? The workflow seems to be installed correctly, and the beer icon appears as I type "emoji", but when I hit enter to invoke the emoji search Alfred takes me to its standard Google search. Any ideas?

**Comment by jsumners** [comment]
I have never encountered this issue. Try debugging the workflow to see what is happening https://www.alfredapp.com/help/workflows/advanced/debugger/

**Comment by dsrjarman** [comment]
Hi James, thanks for the reply. The emoji picker has settled down and works as advertised. I didn't do anything to prompt this... maybe a restart of Alfred did it? Either way, all fine.

**Comment by jsumners** [comment]
👍
