### ISSUE TITLE
Feature to add random emojis

### ISSUE THREAD

**Issue by lnunno** [jsumners/alfred-emoji#37]
Would be cool if this could generate a number of random emojis e.g. `emoji random 2` could generate 2 random emojis to be pasted in.

**Comment by jsumners** [comment]
PRs are welcome.

**Comment by rmm5t** [comment]
🤔 My vote would be a 👎on this. I can't think of any reasonable use-case where a feature like this would get used. Given that this doesn't require any emoji preview, perhaps this is something that should be a separate workflow altogether.

Also, not sure what the syntax should be. but a "random" keyword would interfere with existing emoji.

![Monosnap 2020-03-12 20-12-11](https://user-images.githubusercontent.com/740/76583082-d8e8cd00-649d-11ea-98c0-30c4a0e9d2d8.png)
