### ISSUE TITLE
keyboard shortcut mapping

### ISSUE THREAD

**Issue by avishaan** [jsumners/alfred-emoji#42]
The keyboard shortcuts you have are a little different than most of the other packages I've used (including some built in ones as well).

I believe "return" should paste the emoji into the current text field
"cmd-c" should copy to clipboard

I don't believe the other commands have commonly used equivalents so they can either stay as is or adapt accordingly

Overall love the workflow!

**Comment by jsumners** [comment]
When I type `1+1` into Alfred and press "enter", I get `2` in my clipboard.

When I type `1+1` into Alfred and press "cmd+enter", I get nothing added to the foremost window.

The default for Alfred when pressing "enter" is to copy the result to the clipboard. The "cmd+enter" combination is a mechanism added by this workflow to 1. keep the Alfred established defaults and 2. provide the functionality to "auto paste" the result into the foremost window.
