### ISSUE TITLE
Some of the woman emojis aren't correct and uses gender-inclusive instead

### ISSUE THREAD

**Issue by dvcrn** [jsumners/alfred-emoji#44]
For example 🙅‍♀️ (https://emojipedia.org/woman-gesturing-no/) is displayed as the genderless version (https://emojipedia.org/person-gesturing-no/) for me instead of the correct female one

<img width="605" alt="Screen Shot 2020-11-25 at 11 49 47" src="https://user-images.githubusercontent.com/688326/100176828-52352c80-2f14-11eb-9b9d-e194929ff1c2.png">

Same for the 🙆‍♀️ emoji:

<img width="605" alt="Screen Shot 2020-11-25 at 11 50 23" src="https://user-images.githubusercontent.com/688326/100176910-6d07a100-2f14-11eb-8639-18822be093d6.png">

**Comment by jsumners** [comment]
Which version of macOS?

**Comment by dvcrn** [comment]
Ah sorry, this is on Big Sur 11.0.1. The emoji is pickable from the emoji/character viewer just fine 

<img width="392" alt="Screen Shot 2020-11-25 at 12 33 39" src="https://user-images.githubusercontent.com/688326/100179957-7431ad80-2f1a-11eb-9d29-b50981e62a27.png">

**Comment by jsumners** [comment]
If you build the package from source does it exhibit the problem?

**Comment by ruohola** [comment]
@jsumners Yes it does.

**Comment by jsumners** [comment]
@ruohola thanks. Looks like some sort of bug then.

**Comment by kemayo** [comment]
I should say, I think the requirements for actually fixing this one (without monkeypatching emojilib) probably take it out of the "good first issue" label. 😁
