### ISSUE TITLE
To add skin_tone `random` value

### ISSUE THREAD

**Issue by oscard0m** [jsumners/alfred-emoji#45]
To add `random` as an option so every time an emoji with skin-tone is selected with a random skin-tone (from 1 to 5).

If you think this is an interesting feature I would be happy to open a PR so I get familiar with Alfred workflows :)

**Comment by jsumners** [comment]
I'm not clear how this would be implemented, but you are welcome to attempt it.

**Comment by dominguezcelada** [comment]
> I'm not clear how this would be implemented, but you are welcome to attempt it.

Drafted a PR. If you think the approach is the right one I will go for tests, testing it in local and updating the README
