### ISSUE TITLE
Enable `Dismiss stale pull request approvals when new commits are pushed` option for pull requests

### ISSUE THREAD

**Issue by dominguezcelada** [jsumners/alfred-emoji#49]
To require a re-review of a pull request if somebody adds new commits to an approved pull request.

![image](https://user-images.githubusercontent.com/2574275/101467434-9a0b7900-3942-11eb-8c38-bdfacbc7997f.png)

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-required-reviews-for-pull-requests

**Comment by jsumners** [comment]
I can see the point in a large project, but I don't think it's really needed here. Is there a reason you think it should be enabled here?

**Comment by dominguezcelada** [comment]
I noticed it in this PR: https://github.com/jsumners/alfred-emoji/pull/46#pullrequestreview-547207083 but I just noticed I'm not able to merge myself so... I think it's not critical this feature :)
