### ISSUE TITLE
Automatic update notification keeps popping up, but failing

### ISSUE THREAD

**Issue by NeighNeighNeigh** [jsumners/alfred-emoji#54]
All of a sudden every time I use the (wonderful) emoji workflow, I get a OS notification saying the workflow is updating. I ran debug and am seeing this error at the very end of the console output:
`[12:02:17.759] ERROR: Emoji search[Run Script] The file /var/folders/v7/0gb14sxs36x6m_pydm5whnbm0000gn/T/tmp.YriP7MDg.alfredworkflow does not exist. `

**Comment by jsumners** [comment]
It must be some sort of sandbox issue. I think we could refactor this code to reference a file in `/tmp` instead: https://github.com/jsumners/alfred-emoji/blob/d48ff085fb94b503cbf9409d0e3dee8f3f65b05c/src/update.sh#L29-L32

Maybe:

```
tmpfile=/tmp/$(dd if=/dev/urandom bs=16 count=1 2>/dev/null | shasum | cut -d' ' -f1).alfredworkflow
```

**Comment by jsumners** [comment]
🤔 removing `--silent` from the `curl` results in:

```
[20:38:05.841] ERROR: Emoji search[Run Script] curl: (3) URL using bad/illegal format or missing URL
```

**Comment by jsumners** [comment]
I found the problem. I uploaded the file as a new name on the 1.10.0 release. The update script is going to need to be updated to accommodate macOS 10 and macOS 11.

For now, I have adjusted the 1.10.0 release. I think it should work? But GitHub has rate limited me for a while. So I can't fully test it as an anonymous user until the limit expires.

**Comment by NeighNeighNeigh** [comment]
Hey thanks for taking a look into this so quickly.
So I downloaded the latest workflow [from here](https://github.com/jsumners/alfred-emoji/releases/tag/v1.10.0)
But trying to import into Alfred throws this error:
<img width="419" alt="image" src="https://user-images.githubusercontent.com/4795315/105436437-4c10c180-5cb3-11eb-818b-f89b26a96aa6.png">
_Oops, unable to import! The workflow you are trying to import is invalid._

**Comment by jsumners** [comment]
Well that's not good. It comes directly from https://github.com/jsumners/alfred-emoji/actions/runs/475758355

At the moment, all I can suggest is to clone the repository and run `build.sh` locally to generate the new package.

**Comment by NeighNeighNeigh** [comment]
Okay umm it seems to be working fine now. This is likely me just not really understanding what's going on... but did your fix auto-update at my end and now the problem is fixed?

**Comment by jsumners** [comment]
If you built your own package and installed it, you're just running the latest version. I still need to develop and push out a fix for this issue. It's likely to be a disabling of the auto-update system until I can solve other issues like #52.

**Comment by NeighNeighNeigh** [comment]
Okay no worries, I’ll leave it with you and check back in when you’ve updated. Thanks for such a great workflow, I use it many time each day.

**Comment by cfurrow** [comment]
FYI, in case it's helpful to others, I was also having a script-update issue as mentioned in the original post, but after pulling down the repo (commit d48ff08) and doing the following:

```
npm install
./build.sh
```

Then opening up the output `alfred-emoji.alfredworkflow` file, it seems to have fixed the issue I was seeing in the debugger logs about not finding a file, or whatever.

**Comment by ArtemGordinsky** [comment]
Same here, also solved by building from source.

Does this have something to do with the fact that the [latest release](https://github.com/jsumners/alfred-emoji/releases/tag/v1.10.0), unlike the previous ones, does not have a workflow file attached?

**Comment by jsumners** [comment]
https://github.com/jsumners/alfred-emoji/issues/54#issuecomment-765063029

**Comment by jsumners** [comment]
At this point, I don't have a system on the latest macOS 10 in order to build a package to upload to the latest release. I need to put together a VM to do it and have not had the time.

See my readme https://github.com/jsumners/jsumners

**Comment by rmm5t** [comment]
> Does this have something to do with the fact that the latest release, unlike the previous ones, does not have a workflow file attached?

Yes, very likely.

Let me try to remedy this.

**Comment by rmm5t** [comment]
Fixed. I added the workflow binary to the 1.10.0 github release.

**Comment by jsumners** [comment]
Thank you @rmm5t  for saving the day yet again.

**Comment by NeighNeighNeigh** [comment]
Yes thank you so much :)

**Comment by sn0wyfall** [comment]
Will this be released as an update soon? This issue has plagued me for nearly a year I think

**Comment by jsumners** [comment]
Uh, it has not been a year. This happened with the latest release. But you can manually download from the releases page and it should resolve the issue if you are still seeing it.

**Comment by sn0wyfall** [comment]
Oh maybe it's half a year then. But it's definitely been happening to me ever since I installed it which was at least like 6 months ago
