### ISSUE TITLE
Set default action on ENTER

### ISSUE THREAD

**Issue by gabrielwhite** [jsumners/alfred-emoji#56]
This workflow is great.

Suggested improvement: set default action on pressing ENTER.

I'm used to actioning items in Alfred with ENTER, and by default I'd like the emoji pasted into app I'm using (rather than copied into the clipboard).

Thanks!

**Comment by rmm5t** [comment]
This functionality already exists. 

Just set the `snippetapp` environment variable (to any value) in the workflow configuration to change the behavior to always paste the emoji character regardless of how the workflow is instantiated.


![](https://content.invisioncic.com/r229491/monthly_2019_02/image.png.d9e41739eadd68a074879cb6755d0e8e.png)

**Comment by gabrielwhite** [comment]
Thanks!

**Comment by berters** [comment]
> This functionality already exists.
> 
> Just set the `snippetapp` environment variable (to any value) in the workflow configuration to change the behavior to always paste the emoji character regardless of how the workflow is instantiated.
> 
> ![](https://camo.githubusercontent.com/46d4d6ed84eda938a983e4de070ff066908e5200d3442bcf859eacf55f31f935/68747470733a2f2f636f6e74656e742e696e766973696f6e6369632e636f6d2f723232393439312f6d6f6e74686c795f323031395f30322f696d6167652e706e672e64396534313733396561646436386130373438373963623637353564306538652e706e67)

This is brilliant, thank you!
