### ISSUE TITLE
Coffin emoji returns glyph-like emoji and not emoji show in box 

### ISSUE THREAD

**Issue by Mikeaxial** [jsumners/alfred-emoji#59]
Currently receiving the wrong emoji in most application.

As shown in the screenshot below, the coffin icon differs between the actual expected coffin emoji and what is shown in the "Copy (coffin) to clipboard"

<img width="581" alt="Screenshot_2021-06-11__12_00_PM" src="https://user-images.githubusercontent.com/21265160/121715472-ee87e080-caac-11eb-9ccf-608d8635365d.png">

Interestingly, github changes the emoji to the "correct" one when using the workflow here

**Comment by jsumners** [comment]
Duplicate https://github.com/jsumners/alfred-emoji/issues/53
