### ISSUE TITLE
Certain emoji missing i.e. Green Circle 🟢

### ISSUE THREAD

**Issue by adamsiem** [jsumners/alfred-emoji#61]
https://emojipedia.org/large-green-circle/

Thank you!

**Comment by jsumners** [comment]
Which version of macOS was this emoji added?

**Comment by abraver** [comment]
I'm noticing several additional missing emoji, even though they are included in emojilib:

https://emojipedia.org/tamale/
https://emojipedia.org/drop-of-blood/
https://emojipedia.org/fondue/
https://emojipedia.org/adhesive-bandage/

Emojipedia reports these were all added in either 2019 or 2020, so is it just the case that these are too new to be in the latest version of the workflow?

**Comment by jsumners** [comment]
I'm closing this due to lack of response. I assume it will be resolved once we get version 3 sorted and builds running on recent macOS releases.
