### ISSUE TITLE
Gitmoji support

### ISSUE THREAD

**Issue by vitkarpenko** [jsumners/alfred-emoji#70]
Hey! Would it be too out of scope of a project to support [gitmoji](https://gitmoji.dev) keywords? :) Like suggesting ⚡️ on queries "improve" and "perfomance".
I could probably do it myself if it's appropriate, though I'm not well-versed in JS.

I do know that there are some other Alfred workflows for gitmojis, but I don't like them.

Probably it would be okay to enable this as a feature flag (variable) disabled by default.

**Comment by jsumners** [comment]
I am not familiar with those keywords. However, we do not maintain the keywords for each emoji. The keywords are defined by the Unicode spec and the packages we import provide the spec keywords.

**Comment by vitkarpenko** [comment]
Got it. Thank you!
