### ISSUE TITLE
Commonly used emoji no longer showing in list on update

### ISSUE THREAD

**Issue by davidwolfpaw** [jsumners/alfred-emoji#76]
I updated to v1.11.0 yesterday, and the list of recently/commonly used emoji no longer appears when I use the hotkey. I have selected specific emoji several times since then and the list has not repopulated in any way.

This was the method that I would use to select my most commonly used emoji easier than having to type a keyword for them.

Is this a feature purposefully removed, or a bug, or me using the tool incorrectly?

**Comment by jsumners** [comment]
I think packing precomputed "Alfred items" might be the way to solve it. But that introduces other problems. Maybe just removing the default "show all" will solve it; it's possible Alfred will supply the list in this case 🤷‍♂️

**Comment by jsumners** [comment]
> it's possible Alfred will supply the list in this case 🤷‍♂️

Nope.

**Comment by davidwolfpaw** [comment]
Perhaps building a list of emoji as they are used and displaying that? I'm not sure how ordering is done currently, but I do notice that commonly used emoji are surfaced to the top.

Another option (though I realize that this may go against how you want the workflow to function) would be to drop least common emoji from being pulled automatically. Jennifer Daniel has written a fair amount about common emoji usage https://home.unicode.org/emoji/emoji-frequency/

**Comment by jsumners** [comment]
Alfred's heuristics are what determines the list of most used. This workflow does not, and no ability to, store any state.

**Comment by elalemanyo** [comment]
@jsumners But everything stopped working after the update, at least in my case.

**Comment by jsumners** [comment]
@elalemanyo please re-read the thread.

**Comment by davidwolfpaw** [comment]
> Alfred's heuristics are what determines the list of most used. This workflow does not, and has no ability to, store any state.

Gotcha, thanks for clarifying! I appreciate the work done on the workflow thus far, and it's a shame that some sort of limit has been reached.

**Comment by jsumners** [comment]
By the way, when I open the workflow debugger and trigger the workflow I can see the "all emoji" results show up in a timely fashion. I'm not clear what is wrong. @preppeller might be able to help us?

**Comment by kossa** [comment]
For my case I'm getting this error after latest version, so I'm download v1.10.0 but it does not stop to upgrade the version

![image](https://user-images.githubusercontent.com/1175584/153354584-84bf236d-9932-4fb2-954a-9f260beae182.png)

**Comment by jsumners** [comment]
> For my case I'm getting this error after latest version, so I'm downloading v1.10.0 but it does not stop to upgrade the version

You would need to remove the "check for update" portion of the action. I intend to add a mechanism to prevent addition of the update check when creating a local build. But it is unlikely to be soon.

**Comment by berters** [comment]
I experienced this too - just noticed it had already been reported. Nothing useful to add unfortunately, aside from I love this workflow and hope the bug can be ironed out in the future ❤️

**Comment by kossa** [comment]
@berters just download this version https://github.com/jsumners/alfred-emoji/releases/tag/v1.10.0 and prevent it to upgrade(see above how to do it)

**Comment by jsumners** [comment]
Interesting. The list has suddenly started populating again for me on Alfred `4.6.5 [1299]`. This is on a fresh M1 laptop with https://github.com/jsumners/alfred-emoji/releases/tag/v1.12.0 installed. Initially, it was not showing a recently used list. But after a day or two of usage it has started populating. Maybe the cache gets reset on update and it takes Alfred some time to rebuild it?

**Comment by jsumners** [comment]
I am closing this as it seems to be resolved. In addition to the above mentioned system, it's working on my 2019 16" MBP running 10.15.7 and Alfred 4.6.3 [1285].
