### ISSUE TITLE
Not all searches result in unique set of emoji returned

### ISSUE THREAD

**Issue by rmm5t** [jsumners/alfred-emoji#8]
Some emoji searches result in duplicate emoji results. I've got a fix in the works. PR coming soon.

**Screenshot:**
![image 2018-01-06 15-28-08](https://user-images.githubusercontent.com/740/34644580-7eb921c4-f2f6-11e7-8f3b-20acc733bd02.png)

**Comment by jsumners** [comment]
I'm sure it's due to the aliases and/or the attempt at fuzzy searching.

**Comment by rmm5t** [comment]
> I'm sure it's due to the aliases and/or the attempt at fuzzy searching.

Actually, it's the `Set` logic around using raw js objects that aren't actually equal (they're only "deep equal"). 

I've got a fix that also further cleans up the codebase too. Should be a net-negative in terms of lines of code. I also have a test that will prevent future regressions.

**Comment by rmm5t** [comment]
Didn't mean to prematurely close that. Reverted that commit. I'll get a PR out first.
