### ISSUE TITLE
Recently-added emojis don't have thumbnails

### ISSUE THREAD

**Issue by solzard** [jsumners/alfred-emoji#84]
I noticed recently-added emojis (e.g. 🫠, 🫶) don't have thumbnails on search results.

Environment:
macOS 12.3.1
Alfred 4.6.5 [1299]
Workflow v.1.12.0

![Search - Face](https://user-images.githubusercontent.com/29563481/168505315-becbbf2b-1294-4107-a5fd-ae1d2b17d58a.jpg)
![Search - Hand](https://user-images.githubusercontent.com/29563481/168505565-04d37263-9771-487b-a729-5f7199a83a96.jpg)

**Comment by jsumners** [comment]
https://github.com/jsumners/alfred-emoji/blob/680b2ab782e90032d9d6ad41a42eaf9cd5029b2a/Readme.md?plain=1#L10-L19
