### ISSUE TITLE
Consider adding other languages

### ISSUE THREAD

**Issue by gyassine** [jsumners/alfred-emoji#98]
Hello,

First I want to thank you for your work 🥇 . Then I just want to suggest you a new feature : adding other languages. I'm interested in **french** and I have already found a json file that could help you on github :
 
https://github.com/signalapp/emoji-search-index/blob/main/data/fr.json

**Comment by jsumners** [comment]
We do not maintain the search term list at this time. We rely on an upstream library that compiles the search terms from the UTF data set.

Even if we did, or eventually do, maintain the search term list, we wouldn't be able to maintain multiple language sets. It would likely require multiple builds. Further, we don't know any other languages and would not be able to guarantee any correctness in such search term lists.
