### ISSUE TITLE
Removing auto-updater for Alfred Gallery

### ISSUE THREAD

**Issue by vitorgalvao** [jsumners/alfred-emoji#99]
When [the Alfred Gallery](https://www.alfredforum.com/topic/19058-submitting-workflows-for-the-alfred-gallery/) is live, added workflows will be updatable from within Alfred itself. As part of that, a prerequisite for inclusion will be that workflows *not* auto-update themselves. This is to avoid a confusing interaction of crossed updates *and* for security reasons, as Gallery workflows go through a number of checks.

Typically I’d submit the PR for this, but you’re using a bespoke method for the `info.plist` and didn’t want to mess up your organisation. Making a new release helps to speed up the process, but if you prefer to wait let me know and I’ll ping you once the Gallery is live.

**Comment by jsumners** [comment]
Can you provide some more information on how this feature will work? What do we need to do to support it? How will releases work with it?

**Comment by vitorgalvao** [comment]
> Can you provide some more information on how this feature will work?

Alfred itself will check for updates from the Gallery, so users will have the option to update without having to run the workflow.

> What do we need to do to support it? How will releases work with it?

You don’t need to do anything to support it, your process won’t change. You’ll still make releases as usual and we’ll detect when those are out and queue them up for a new review and update in the Gallery.

If you ever need to make a hotfix for someone to test, you can. Then after you make the new release, even that user will be able to update from within Alfred to the version you intended.

**Comment by vitorgalvao** [comment]
We won’t be rebuilding the workflows. We’ll grab **your release**, the `.alfredworkflow` file **you post**, and rehost that one with a signature which ensures that no tampering happened since review, as well as availability. What users will get is the same package as if they had downloaded directly from GitHub.

It’s similar to submitting an app to the App Store. Technically Apple could change it, but they wouldn’t make malicious or breaking changes. In that same vein, there’s no reason for Alfred to deliberately break your workflow.

If it makes you more comfortable, you can hold off until the gallery is live and then you’ll be able to both see how it works, and decide if you want your workflow to be included.

**Comment by jsumners** [comment]
> We’ll grab **your release**, the `.alfredworkflow` file **you post**, and rehost that one with a signature which ensures that no tampering happened since review, as well as availability.

I'm still not clear how this happens.

**Comment by vitorgalvao** [comment]
Are you able to clarify what you don’t understand?

**Comment by vitorgalvao** [comment]
It happens manually. The downloaded workflow is reviewed and a signature is generated so Alfred can check against it and know the downloaded packaged is the same as what was reviewed.

Are you able to shed some light on what’s confusing? I’ve reread the quoted explanation a few times and don’t understand what specifically you find unclear.

**Comment by jsumners** [comment]
This process seems like one step forward and two steps back:

1. It's fantastic that your team is working to resolve the discoverability and update problems for workflows (step forward)
2. Releases get slowed down by a manual process (two steps back)

I'm really uneasy about removing an automated process in favor of a manual one. I'm particularly uneasy about adding a third party human into the process.

**Comment by vitorgalvao** [comment]
A manual process which exists for user security. Plus, it is a process which finds basic flaws and improves workflows. Case in point, the two PRs I’ve sent for this very workflow. It’s far from the only case which has directly benefitted from the process. It results in users getting more reliable workflows with a better understanding of what they can trust.

> I'm particularly uneasy about adding a third party human into the process.

A third-party human which is a first-party in what relates to Alfred. Again, there’s little difference from submitting an app to the App Store except the reviewer knows how to program and handholds you with what exactly needs improving, down to sending code fixes and explaining the reasoning for stuff.

**Comment by jsumners** [comment]
> Plus, it is a process which finds basic flaws and improves workflows. Case in point, the two PRs I’ve sent for this very workflow.

Um, one of your PRs addressed handling of shell input as a result of the lack of complete documentation on Alfred's part. The other was adding a new feature. Neither were a "flaw" in this workflow, per se.

> It’s far from the only case which has directly benefitted from the process. It results in users getting more reliable workflows with a better understanding of what they can trust.

This is now setting you up as the arbiter of what is and is not "good".

> Again, there’s little difference from submitting an app to the App Store

I don't know why you keep bringing up the App Store. I do not have to deal with the app store except to install a few bits of software that choose to only distribute through it. I really don't care what their processes are.

> except the reviewer knows how to program and handholds you with what exactly needs improving, down to sending code fixes and explaining the reasoning for stuff.

Again, this sounds a lot like you are setting yourself up as the ultimate authority on what can and cannot be done. Until this is no longer the case, I think we will be okay with our current distribution mechanism.

**Comment by vitorgalvao** [comment]
> Neither were a "flaw" in this workflow, per se.

Correct. I wasn’t calling them that. They were general improvements.

> This is now setting you up as the arbiter of what is and is not "good".

Not so. I sent pull requests. We could have discussed them further and you had final say in merging. I strive to always make the pull requests make sense for the workflow in question and work with the creator to have it merged.

Plus, your choice to distribute the workflow yourself is never compromised. Nothing changes if you continue as you were.

Anyway, thank you for the fast replies. Do ping me if you change your mind. Have a great week.
